[package]
name = "rust_runtime"
version = "0.1.0"
authors = ["Patrick Norton <patrick.147.norton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.6"
bigdecimal = "0.1.0"
enum-map = "0.6.2"
